#!/usr/bin/env bash
#A loop displaying numbes 1-100
#But is the number is divisible by 3 and 5 prints "FizzBuzz"
#If the number is divisvle by 3 prints "Fizz"
#If the number is divisible by 5 prints "Buzz"

num=1

while [ $num -le 100 ];
do

#Nested if introduced for the contional statemnets

if [ $((num % 3)) -eq 0 ] && [ $((num % 5)) -eq 0 ]; then
echo "FizzBuzz"

elif [ $((num % 3)) -eq 0 ]; then

echo "Fizz"

elif [ $((num % 5)) -eq 0 ]; then

echo "Buzz"

else

echo "$num"

fi

num=$((num + 1)) #Counter for incrementing the value of num by 1

done
