#!/usr/bin/env bash
#Creating a while loop with case scenerio to give out uniform output  until 20
num=1 #counting starting from 1

while [ $num -le 20 ]
do

echo "$num" #prints the current number

case $num in #we use case scenrio to give the desired output
4)

 echo "bad luck from China"
;;

9)

echo "bad luck from Japan"
;;

17)

echo "bad luck from Italy"
;;

esac

num=$((num + 1)) #increamenting the counter by 1
done

