#!/usr/bin/env bash
num=1 #counting starting from 1

while [ $num -le 20 ]
do

echo "$num" #prints the current number

case $num in #we use case scenrio to give the desired output
4)

 echo "bad luck from China"
;;

9)

echo "bad luck from Japan"
;;

17)

echo "bad luck from Italy"
;;

esac

num=$((num + 1)) #increamenting the counter by 1
done

